//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKUS_V1_2018.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sisteman_TEKUSEntities : DbContext
    {
        public sisteman_TEKUSEntities()
            : base("name=sisteman_TEKUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_TEKUS_CLIENTES> TBL_TEKUS_CLIENTES { get; set; }
        public virtual DbSet<TBL_TEKUS_PAIS> TBL_TEKUS_PAIS { get; set; }
        public virtual DbSet<TBL_TEKUS_SERVICIOS> TBL_TEKUS_SERVICIOS { get; set; }
    
        public virtual int SP_DATA_DELETE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DATA_DELETE");
        }
    }
}
