//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKUS_V1_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEKUS_SERVICIOS
    {
        public decimal ID_SERVICIOS { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> VPORHORA { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
        public Nullable<decimal> ID_PAIS { get; set; }
    
        public virtual TBL_TEKUS_CLIENTES TBL_TEKUS_CLIENTES { get; set; }
        public virtual TBL_TEKUS_PAIS TBL_TEKUS_PAIS { get; set; }
    }
}
