//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKUS_V1_2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TEKUS_PAIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TEKUS_PAIS()
        {
            this.TBL_TEKUS_CLIENTES = new HashSet<TBL_TEKUS_CLIENTES>();
            this.TBL_TEKUS_SERVICIOS = new HashSet<TBL_TEKUS_SERVICIOS>();
        }
    
        public decimal ID_PAIS { get; set; }
        public string NOMBRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEKUS_CLIENTES> TBL_TEKUS_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_TEKUS_SERVICIOS> TBL_TEKUS_SERVICIOS { get; set; }
    }
}
